services:
  claude-docker:
    build: .
    container_name: claude-code
    env_file:
      - .env
    volumes:
      - ${HOME}/.claude:/home/claude/.claude
      - ${HOME}/Projects:/home/claude/Projects
      - ${HOME}/.ssh:/home/claude/.ssh:ro
      - ${HOME}/.gitconfig:/home/claude/.gitconfig:ro
      - ./.tmux.conf:/home/claude/.tmux.conf:ro
      - ./.claude.json:/home/claude/.claude.json
      - ./.claude-credentials.json:/home/claude/.claude/.credentials.json
    stdin_open: true
    tty: true
    restart: on-failure
    working_dir: /home/claude/Projects
